# docker-compose.yml
version: '3.8'

services:
  btc-backtester:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_ENV=production
      - SQLALCHEMY_DATABASE_URI=sqlite:////app/data/finance_tracker.db
    restart: unless-stopped

volumes:
  finance_data: